services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./app:/app
      - /app/node_modules  
    ports:
      - "5173:5173"

  prod:
    build:
      context: .
      target: prod
    volumes:
      - ./app:/app
      - /app/node_modules  
    ports:
      - "80:80"
    restart: unless-stopped 