services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./app:/app
      - /app/node_modules  
    ports:
      - "5173:5173"

  prod:
    build:
      context: .
      target: prod
      args:
        - NGINX_CONF_PATH=${NGINX_CONF_PATH}
    volumes:
      - ./app:/app
      - /app/node_modules  
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped 